apiVersion: v2
name: unifi
description: A Helm chart for Unifi Network Controller
type: application
# renovate: depName=unifi
version: "10.0.162-32076-1"
# renovate: depName=unifi
appVersion: "10.0.162-32076-1"
